### ISSUE TITLE
[Feature Request] Sub folders

### ISSUE THREAD

**Issue by jpts** [robwebset/script.videoextras#2]
It'd be really convenient to have sub-folder support, especially for shows with large numbers of extras (I have 245 for one show, for example).

Currently sub-folders are ignored, just having them scanned and included flat would be better a bit better, but ideally it would reflect the folder hierarchy.

**Comment by robwebset** [comment]
Added support to pull in videos in sub-directories, they are currently just added to the list - to create some form of directory structure would be a lot more work.

Included in VideoExtras v100.3.0
