### ISSUE TITLE
VideoExtras and Emby

### ISSUE THREAD

**Issue by mikeB2210** [robwebset/script.videoextras#3]
Hi,
I want to use your Addon VideoExtras with Emby. My movie and TV Series are on a NAS. In Emby I uses direct path to play my movies. Is it possible that you point me in the right direction how to setup your addon with Emby Server.

Thanks

**Comment by robwebset** [comment]
I don't use Emby myself, however I believe others have used Emby and VideoExtras before by setting the "Use Custom Extras Location"

https://github.com/robwebset/script.videoextras/wiki#File_System

Thanks, Rob
