### ISSUE TITLE
Urepo splash screen on every Kodi boot

### ISSUE THREAD

**Issue by TonyPh12345** [robwebset/script.videoextras#4]
Running stock LibreElec Kodi 16.1.  on each boot, I get a "urepo" splash screen, for lack of a better description, which must be closed before interaction with the main menu.

Urepo was banned by Kodi team. So hopefully this addition to script.videoextras doesn't get this banned...

**Comment by robwebset** [comment]
In fact the Kodi team (well actually Ronie and Martijn) decided to ban all the robwebset addons over a disagreement - so makes no difference - and it was actually Zag allowing the robwebset addons into the URepo that caused Martijn to ban the URepo - but Zag knew that Martijn was just waiting for an excuse, so told me to go ahead and add them to URepo.

**Comment by TonyPh12345** [comment]
Hi, Rob!  The issue was more about the somewhat intrusive URepo splash screen on every boot that one has to manually close before the main menu appears.

What can be done about that?

**Comment by robwebset** [comment]
You need to install the URepo repository and then do an update of all the addons that you use from the robwebset repository:

https://github.com/robwebset/repository.robwebset/blob/master/README.md
